-- GENERATED by scripts/generate-seed.ts from config/seed/*. Do not edit by hand.
-- Idempotent: safe to re-run. Existing rows are left untouched so admin edits survive.

insert into public.categories (slug, display_name, short_name, conflict_key, aliases, landing_page_copy, priority, active)
values
  ('hvac', 'HVAC', 'HVAC', 'hvac', array['Air Conditioning', 'Heating', 'Furnace Repair']::text[], 'Stay visible in Clawson before the furnace stops heating or the AC stops cooling.', 1, true),
  ('plumbing', 'Plumbing', 'plumbing', 'plumbing', array['Plumber', 'Drain Service']::text[], 'Put your company in front of local households before the leak, clogged drain or plumbing emergency happens.', 2, true),
  ('roofing', 'Roofing', 'roofing', 'roofing', array['Roofer']::text[], 'Put your company in the neighborhood before the homeowner discovers the leak, missing shingles or storm damage.', 3, true),
  ('electrician', 'Electrician', 'electrical', 'electrical', array['Electrical']::text[], 'Build local recognition before the homeowner needs electrical repairs, upgrades or installation work.', 4, true),
  ('garage-door', 'Garage Door', 'garage door', 'garage-door', '{}'::text[], null, 5, true),
  ('restoration', 'Restoration', 'restoration', 'restoration', array['Water Damage', 'Fire Damage']::text[], null, 6, true),
  ('basement-foundation-waterproofing', 'Basement / Foundation / Waterproofing', 'basement and foundation', 'basement-foundation', array['Waterproofing', 'Foundation Repair']::text[], null, 7, true),
  ('kitchen-bath-remodeling', 'Kitchen & Bath Remodeling', 'remodeling', 'remodeling', array['Kitchen Remodeling', 'Bathroom Remodeling']::text[], null, 8, true),
  ('windows-doors', 'Windows & Doors', 'windows and doors', 'windows-doors', '{}'::text[], null, 9, true),
  ('tree-service', 'Tree Service', 'tree service', 'tree-service', array['Tree Removal', 'Arborist']::text[], null, 10, true),
  ('pest-control', 'Pest Control', 'pest control', 'pest-control', array['Exterminator']::text[], null, 11, true),
  ('landscaping-lawn', 'Landscaping / Lawn', 'landscaping', 'landscaping', array['Lawn Care', 'Landscaping']::text[], null, 12, true),
  ('junk-removal', 'Junk Removal', 'junk removal', 'junk-removal', array['Hauling']::text[], null, 13, true),
  ('painting', 'Painting', 'painting', 'painting', array['Painter']::text[], null, 14, true),
  ('flooring-carpet', 'Flooring / Carpet', 'flooring', 'flooring', array['Carpet', 'Flooring']::text[], null, 15, true),
  ('auto-repair', 'Auto Repair', 'auto repair', 'auto-repair', array['Mechanic']::text[], null, 16, true),
  ('dentist', 'Dentist', 'dental', 'dental', array['Dental Practice']::text[], 'Build familiarity with local households looking for a dental practice close to home.', 17, true),
  ('realtor', 'Realtor', 'real estate', 'real-estate', array['Real Estate Agent']::text[], 'Keep your name visible in the community before the next homeowner decides to buy or sell.', 18, true),
  ('chiropractic-physical-therapy', 'Chiropractic / Physical Therapy', 'chiropractic and physical therapy', 'chiropractic-pt', array['Chiropractor', 'Physical Therapy']::text[], null, 19, true),
  ('pizza-takeout', 'Pizza / Takeout', 'pizza', 'pizza-takeout', array['Pizza', 'Takeout']::text[], 'Give local households a reason to keep the mailer nearby with an offer they can actually use.', 20, true),
  ('veterinary', 'Veterinary', 'veterinary', 'veterinary', array['Veterinarian', 'Animal Hospital']::text[], null, 21, true),
  ('house-cleaning', 'House Cleaning', 'house cleaning', 'house-cleaning', array['Maid Service']::text[], null, 22, true),
  ('fence-deck', 'Fence / Deck', 'fence and deck', 'fence-deck', array['Fencing', 'Decks']::text[], null, 23, true),
  ('gutter', 'Gutter', 'gutter', 'gutter', array['Gutter Cleaning', 'Gutter Guards']::text[], null, 24, true),
  ('moving', 'Moving', 'moving', 'moving', array['Movers']::text[], null, 25, true),
  ('insurance', 'Insurance', 'insurance', 'insurance', array['Insurance Agent']::text[], null, 26, true),
  ('med-spa', 'Med Spa', 'med spa', 'med-spa', '{}'::text[], null, 27, true),
  ('pet-grooming', 'Pet Grooming', 'pet grooming', 'pet-grooming', array['Dog Grooming']::text[], null, 28, true),
  ('salon-barber', 'Salon / Barber', 'salon and barber', 'salon-barber', array['Hair Salon', 'Barbershop']::text[], null, 29, true),
  ('optometrist', 'Optometrist', 'eye care', 'optometry', array['Eye Doctor']::text[], null, 30, true)
on conflict (slug) do nothing;

insert into public.campaigns (slug, name, market, state, status, is_active, price_cents, max_advertisers, planned_reach, reach_is_estimated, included_revisions, reservation_minutes)
values ('clawson-founding-edition', 'Founder’s Edition', 'Clawson', 'Michigan', 'OPEN', true, 35000, 20, 5800, true, 1, 30)
on conflict (slug) do nothing;
