import { site } from "@/config/site";
import type { CampaignConfig } from "@/types/campaign";
import { formatCampaignPrice, getReachLabel } from "./format";

export type FaqItem = { id: string; q: string; a: string };

/** Supplied FAQ copy, with price/reach/revisions pulled from config. */
export function getFaq(campaign: CampaignConfig): FaqItem[] {
  const price = formatCampaignPrice(campaign);
  const edition = campaign.campaignName;
  const revWord = ["No", "One", "Two", "Three"][campaign.includedRevisions] ?? String(campaign.includedRevisions);
  const reachAnswer = campaign.reachIsEstimated
    ? `The ${edition} is currently planned for ${getReachLabel(campaign)}. Final quantity depends on the USPS carrier routes selected and will be confirmed before printing.`
    : `The ${edition} is planned for ${getReachLabel(campaign)}, based on the USPS carrier routes selected for the edition.`;

  return [
    {
      id: "includes",
      q: `What does the ${price} include?`,
      a: `Your category-exclusive placement, ad design, proofing, printing and mailing for the ${edition}. There are no mandatory recurring charges.`,
    },
    { id: "reach", q: "How many residences will receive it?", a: reachAnswer },
    {
      id: "competitors",
      q: "Will another business in my industry appear on it?",
      a: "No. We accept one advertiser per category on each edition. Related services may be grouped into the same conflict category when they directly compete.",
    },
    {
      id: "hold",
      q: "Can you hold my category?",
      a: `We don't hold categories based on interest alone. When you click Claim, the category is held for you for about ${campaign.reservationMinutes} minutes while you complete checkout; it becomes yours once payment is confirmed.`,
    },
    {
      id: "need-ad",
      q: "Do I need an ad already?",
      a: "No. Send us your logo, business information and offer or message and we'll build it for you.",
    },
    {
      id: "artwork",
      q: "What if I already have artwork?",
      a: "You can upload it after checkout. We'll review it for compatibility with the available placement.",
    },
    {
      id: "approve",
      q: "Do I get to approve the ad?",
      a: "Yes. You receive a digital proof before printing. Nothing goes to print until your advertisement has been approved.",
    },
    {
      id: "revisions",
      q: "How many revisions are included?",
      a: `${revWord} revision${campaign.includedRevisions === 1 ? " is" : "s are"} included. Changes required because of an error on our side do not count against your included revision${campaign.includedRevisions === 1 ? "" : "s"}.`,
    },
    {
      id: "guarantee",
      q: "Do you guarantee calls or leads?",
      a: "No. We guarantee the agreed advertising fulfillment, not a specific business result.",
    },
    {
      id: "no-response",
      q: "What if nobody responds to my ad?",
      a: "Advertising response can depend on your offer, category, timing, reputation and whether residents currently need your service. The purpose of the edition is local visibility and category-exclusive exposure, not a guaranteed response rate.",
    },
    {
      id: "doesnt-happen",
      q: `What if the ${edition} doesn't happen?`,
      a: `If we cannot fulfill the ${edition} by the outside fulfillment date stated at checkout, you may choose a full refund or transfer your payment to the next edition.`,
    },
    {
      id: "subscription",
      q: "Is this a subscription?",
      a: `No. Your ${price} ${edition} purchase is one time.`,
    },
    { id: "recharge", q: "Will you automatically charge me again?", a: "No." },
    {
      id: "location",
      q: `Do I have to be located in ${campaign.marketName}?`,
      a: `Not necessarily. Your business must legitimately serve customers in the ${campaign.marketName} market.`,
    },
    {
      id: "tracking",
      q: "Can I track anything?",
      a: "We can include a trackable QR link in your advertisement. QR scans can provide one source of engagement data, but they should not be interpreted as every response generated by the mailing.",
    },
    {
      id: "after-pay",
      q: "What happens after I pay?",
      a: "Your category is secured as soon as payment is confirmed. We'll collect your ad materials in the next step, create your ad, send you a proof to approve, and keep you updated through printing and mailing.",
    },
    {
      id: "talk",
      q: "Can I talk to someone?",
      a: `Of course. Email ${site.email.public}. A call is available if you need one, but it isn't required to purchase.`,
    },
  ];
}

/** Short list used on the homepage and category pages. */
export const KEY_FAQ_IDS = [
  "includes",
  "reach",
  "competitors",
  "hold",
  "guarantee",
  "doesnt-happen",
  "subscription",
  "after-pay",
  "talk",
];
