import type { Metadata } from "next";
import { PageHeader } from "@/components/ui/page-header";
import { Pending } from "@/components/ui/pending";
import { site } from "@/config/site";
import {
  formatCampaignDate,
  formatCampaignPrice,
  formatRevisions,
  getActiveCampaign,
  getReachLabel,
} from "@/lib/campaign";

export const metadata: Metadata = {
  title: "Advertiser Terms",
  description: "Advertiser terms for The Clawson Local.",
  alternates: { canonical: "/terms" },
};

// NOTE: Drafted from the product spec. Have it reviewed by counsel before
// sales open, then bump site.termsVersion.
export default async function TermsPage() {
  const campaign = await getActiveCampaign();
  const price = formatCampaignPrice(campaign);
  const outside = formatCampaignDate(campaign.outsideFulfillmentDate);
  const sections: [string, React.ReactNode][] = [
    [
      "What you are buying",
      <>
        Your payment of {price} buys one advertising placement on {site.name} {campaign.campaignName}, category
        exclusivity for your category on that edition, production of the edition, and distribution to the selected{" "}
        {campaign.marketName} postal routes. It is a one-time charge. There is no subscription and no recurring charge.
      </>,
    ],
    [
      "Reach",
      <>
        {campaign.reachIsEstimated
          ? `The edition is currently planned for ${getReachLabel(campaign)}. Final quantity depends on the USPS carrier routes selected and will be published before printing.`
          : `The edition is planned for ${getReachLabel(campaign)} based on the USPS carrier routes selected.`}
      </>,
    ],
    [
      "Category exclusivity",
      <>
        We accept one advertiser per category on each edition. Related services that directly compete may be grouped
        into the same conflict category. Your category is secured only when payment is completed; we do not hold
        categories based on interest alone. Checkout reservations last {campaign.reservationMinutes} minutes.
      </>,
    ],
    [
      "No guaranteed results",
      <>
        We guarantee the agreed advertising fulfillment, not a specific business result. We do not promise any number
        of calls, leads, customers or sales. QR scans, where included, are one source of engagement data and do not
        capture every response generated by the mailing.
      </>,
    ],
    [
      "Your ad, proofs and revisions",
      <>
        After payment you will submit your materials through a private intake link. We design your ad from the assets
        you supply and send a digital proof. Your placement includes {formatRevisions(campaign)}; changes required
        because of an error on our side do not count against it. Nothing prints until you approve the proof. By
        approving, you confirm that the business name, phone number, website, offer, pricing, dates and other factual
        information shown are accurate. You are responsible for the accuracy and lawfulness of the claims and offers
        you submit.
      </>,
    ],
    [
      "Fulfillment",
      <>
        If we cannot fulfill the {campaign.campaignName} by the outside fulfillment date stated at checkout, you may
        choose a full refund or transfer your payment to the next edition. Outside fulfillment date:{" "}
        <Pending value={outside} label="Outside fulfillment date" />.
      </>,
    ],
    [
      "Contact",
      <>
        Questions about these terms: <a href={`mailto:${site.email.public}`} className="text-accent underline">{site.email.public}</a>.
        Business: <Pending value={site.legalName} label="Legal name" />.
      </>,
    ],
  ];
  return (
    <>
      <PageHeader eyebrow="Advertiser terms" title="Advertiser Terms">
        <p className="text-sm text-ink-muted">Terms version {site.termsVersion}</p>
      </PageHeader>
      <div className="container-page max-w-3xl pb-16">
        <ol className="space-y-8">
          {sections.map(([h, body], i) => (
            <li key={h}>
              <h2 className="headline text-2xl">
                {i + 1}. {h}
              </h2>
              <p className="mt-2 text-ink-soft">{body}</p>
            </li>
          ))}
        </ol>
      </div>
    </>
  );
}
