/**
 * Generates supabase/seed.sql from the seed config files.
 * Run: npm run db:seed:generate
 */
import { writeFileSync } from "node:fs";
import { foundingCampaignSeed as cp } from "../config/seed/campaign.ts";
import { categorySeeds } from "../config/seed/categories.ts";

const q = (v: string | null) => (v === null ? "null" : `'${v.replace(/'/g, "''")}'`);
const arr = (v: string[]) => (v.length ? `array[${v.map(q).join(", ")}]::text[]` : "'{}'::text[]");

const categories = categorySeeds
  .map(
    (c) =>
      `  (${q(c.slug)}, ${q(c.displayName)}, ${q(c.shortName)}, ${q(c.conflictKey)}, ${arr(c.aliases)}, ${q(c.landingLine)}, ${c.priority}, ${c.active})`,
  )
  .join(",\n");

const sql = `-- GENERATED by scripts/generate-seed.ts from config/seed/*. Do not edit by hand.
-- Idempotent: safe to re-run. Existing rows are left untouched so admin edits survive.

insert into public.categories (slug, display_name, short_name, conflict_key, aliases, landing_page_copy, priority, active)
values
${categories}
on conflict (slug) do nothing;

insert into public.campaigns (slug, name, market, state, status, is_active, price_cents, max_advertisers, planned_reach, reach_is_estimated, included_revisions, reservation_minutes)
values (${q(cp.slug)}, ${q(cp.name)}, ${q(cp.market)}, ${q(cp.state)}, ${q(cp.status)}, ${cp.isActive}, ${cp.priceCents}, ${cp.maxAdvertisers}, ${cp.plannedReach}, ${cp.reachIsEstimated}, ${cp.includedRevisions}, ${cp.reservationMinutes})
on conflict (slug) do nothing;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`Wrote supabase/seed.sql (${categorySeeds.length} categories, 1 campaign).`);
