/**
 * Upload rules, enforced on the server (the browser's checks are only a
 * convenience). Storage paths are generated by the server; the original
 * filename is kept, sanitized, for display only.
 */

export const ASSET_KINDS = ["logo", "photo", "artwork"] as const;
export type AssetKind = (typeof ASSET_KINDS)[number];

export const CONTENT_TYPES = {
  "image/png": "png",
  "image/jpeg": "jpg",
  "image/svg+xml": "svg",
  "application/pdf": "pdf",
  "image/webp": "webp",
} as const;
export type AllowedContentType = keyof typeof CONTENT_TYPES;

const MB = 1024 * 1024;

export const FILE_RULES: Record<AssetKind, { types: readonly AllowedContentType[]; maxBytes: number; label: string; accept: string }> = {
  logo: { types: ["image/png", "image/jpeg", "image/svg+xml", "application/pdf"], maxBytes: 10 * MB, label: "PNG, JPG, SVG or PDF, up to 10 MB", accept: ".png,.jpg,.jpeg,.svg,.pdf" },
  photo: { types: ["image/png", "image/jpeg", "image/webp"], maxBytes: 15 * MB, label: "PNG, JPG or WebP, up to 15 MB", accept: ".png,.jpg,.jpeg,.webp" },
  artwork: { types: ["application/pdf", "image/png", "image/jpeg"], maxBytes: 50 * MB, label: "PDF, PNG or JPG, up to 50 MB", accept: ".pdf,.png,.jpg,.jpeg" },
};

export const MAX_PHOTOS = 3;

export function isAssetKind(v: unknown): v is AssetKind {
  return typeof v === "string" && (ASSET_KINDS as readonly string[]).includes(v);
}

export type UploadRejection = "invalid_kind" | "unsupported_type" | "file_too_large" | "empty_file";

/** Check a declared upload before any storage URL is issued. */
export function checkDeclaredUpload(kind: unknown, contentType: unknown, size: unknown): UploadRejection | null {
  if (!isAssetKind(kind)) return "invalid_kind";
  const rule = FILE_RULES[kind];
  if (typeof contentType !== "string" || !(rule.types as readonly string[]).includes(contentType)) return "unsupported_type";
  if (typeof size !== "number" || !Number.isInteger(size) || size <= 0) return "empty_file";
  if (size > rule.maxBytes) return "file_too_large";
  return null;
}

/** Display-only filename: no paths, no control or odd characters, bounded length. */
export function sanitizeFilename(name: unknown): string {
  const base = String(name ?? "")
    .split(/[\\/]/)
    .pop()!
    .normalize("NFKC")
    .replace(/[^A-Za-z0-9._ -]+/g, "_")
    .replace(/\s+/g, " ")
    .replace(/^[.\s_-]+/, "")
    .trim();
  const clipped = base.length > 120 ? base.slice(0, 60) + "…" + base.slice(-59) : base;
  return clipped || "file";
}

/**
 * The file's real type from its first bytes. SVG is recognized as XML text
 * containing an <svg> root; it is stored privately and only ever offered as a
 * download, never rendered.
 */
export function sniffContentType(head: Uint8Array): AllowedContentType | null {
  const b = head;
  const starts = (sig: number[], at = 0) => sig.every((v, i) => b[at + i] === v);
  if (starts([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) return "image/png";
  if (starts([0xff, 0xd8, 0xff])) return "image/jpeg";
  if (starts([0x25, 0x50, 0x44, 0x46, 0x2d])) return "application/pdf"; // %PDF-
  if (starts([0x52, 0x49, 0x46, 0x46]) && starts([0x57, 0x45, 0x42, 0x50], 8)) return "image/webp"; // RIFF....WEBP
  const text = new TextDecoder("utf-8", { fatal: false }).decode(b).replace(/^﻿/, "").trimStart().toLowerCase();
  if ((text.startsWith("<?xml") || text.startsWith("<svg") || text.startsWith("<!--") || text.startsWith("<!doctype svg")) && text.includes("<svg")) {
    return "image/svg+xml";
  }
  return null;
}
